name: Dependabot PR comment

on:
  pull_request:
    paths:
      - "pnpm-lock.yaml"

permissions:
  contents: read
  pull-requests: write

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This PR will need formatting and testing locally. Run `pnpm test` locally to reformat and test the PR branch with the full local test suite.'
            })
