name: Linting
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Check code styling
        run: pnpm lint
      - name: Check code for issues
        run: pnpm pretty-check
