name: Playwright tests
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      AUTH_URL: ${{ secrets.AUTH_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright with deps
        run: npx playwright install --with-deps
      - name: Cache Next.js build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Build application ready to test
        run: pnpm build
      - name: Run public site playwright tests
        run: npx playwright test tests/public/
      - uses: actions/upload-artifact@v5
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
